products = [
    {
        '_id': 1,
        'name': 'Laptop Repair',
        'image': '/images/laptop.jpg',
        'description': 'Professional laptop repair services',
        'brand': 'Computer Pro',
        'category': 'Repair',
        'price': 99.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 20,
    },
    {
        '_id': 2,
        'name': 'Desktop Repair',
        'image': '/images/desktop.jpg',
        'description': 'Fast and reliable desktop computer repair',
        'brand': 'Tech Experts',
        'category': 'Repair',
        'price': 79.99,
        'countInStock': 15,
        'rating': 4.8,
        'numReviews': 35,
    },
    {
        '_id': 3,
        'name': 'Hardware Upgrade',
        'image': '/images/hardware.jpg',
        'description': 'Upgrade your computer components',
        'brand': 'Upgrade Hub',
        'category': 'Upgrade',
        'price': 199.99,
        'countInStock': 5,
        'rating': 4.3,
        'numReviews': 12,
    },
    {
        '_id': 4,
        'name': 'Software Installation',
        'image': '/images/software.jpg',
        'description': 'Professional software installation and setup',
        'brand': 'Software Solutions',
        'category': 'Software',
        'price': 49.99,
        'countInStock': 20,
        'rating': 4.7,
        'numReviews': 28,
    },
    {
        '_id': 5,
        'name': 'Data Recovery',
        'image': '/images/data.jpg',
        'description': 'Recover your lost data safely',
        'brand': 'Data Rescue',
        'category': 'Data',
        'price': 149.99,
        'countInStock': 8,
        'rating': 4.9,
        'numReviews': 42,
    },
]
